name: Build Executables

on:
  push:
    tags:
      - 'v*'  # 添加标签触发条件，匹配 v1.0.0 这样的标签

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build EXE (CLI Version)
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Build EXE (GUI Version)
      run: |
        # 创建新的spec文件
        echo "# -*- mode: python ; coding: utf-8 -*-" > CursorProGUI.spec
        echo "block_cipher = None" >> CursorProGUI.spec
        echo "a = Analysis(['cursor_pro_gui.py'], pathex=['$(pwd)'], binaries=[], datas=[('icons', 'icons'), ('translations', 'translations')], hiddenimports=[], hookspath=[], runtime_hooks=[], excludes=[], win_no_prefer_redirects=False, win_private_assemblies=False, cipher=block_cipher, noarchive=False)" >> CursorProGUI.spec
        echo "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)" >> CursorProGUI.spec
        echo "exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [], name='CursorProGUI', debug=False, bootloader_ignore_signals=False, strip=False, upx=True, upx_exclude=[], runtime_tmpdir=None, console=False, icon='icons/logo.ico')" >> CursorProGUI.spec
        
        # 使用 spec 文件构建
        pyinstaller CursorProGUI.spec
        
    - name: Upload Windows CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-Windows
        path: dist/CursorPro.exe
        
    - name: Upload Windows GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorProGUI-Windows
        path: dist/CursorProGUI.exe

  build-macos-arm64:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build MacOS ARM executable (CLI Version)
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Build MacOS ARM executable (GUI Version)
      run: |
        # 创建新的spec文件
        echo "# -*- mode: python ; coding: utf-8 -*-" > CursorProGUI.spec
        echo "block_cipher = None" >> CursorProGUI.spec
        echo "a = Analysis(['cursor_pro_gui.py'], pathex=['$(pwd)'], binaries=[], datas=[('icons', 'icons'), ('translations', 'translations')], hiddenimports=[], hookspath=[], runtime_hooks=[], excludes=[], win_no_prefer_redirects=False, win_private_assemblies=False, cipher=block_cipher, noarchive=False)" >> CursorProGUI.spec
        echo "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)" >> CursorProGUI.spec
        echo "exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [], name='CursorProGUI', debug=False, bootloader_ignore_signals=False, strip=False, upx=True, upx_exclude=[], runtime_tmpdir=None, console=False)" >> CursorProGUI.spec
        
        # 使用 spec 文件构建
        pyinstaller CursorProGUI.spec
        
    - name: Upload MacOS ARM CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-MacOS-ARM64
        path: dist/CursorPro
        
    - name: Upload MacOS ARM GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorProGUI-MacOS-ARM64
        path: dist/CursorProGUI

  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        # 安装Qt依赖
        sudo apt-get update
        sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0
        
    - name: Build Linux executable (CLI Version)
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Build Linux executable (GUI Version)
      run: |
        # 创建新的spec文件
        echo "# -*- mode: python ; coding: utf-8 -*-" > CursorProGUI.spec
        echo "block_cipher = None" >> CursorProGUI.spec
        echo "a = Analysis(['cursor_pro_gui.py'], pathex=['$(pwd)'], binaries=[], datas=[('icons', 'icons'), ('translations', 'translations')], hiddenimports=[], hookspath=[], runtime_hooks=[], excludes=[], win_no_prefer_redirects=False, win_private_assemblies=False, cipher=block_cipher, noarchive=False)" >> CursorProGUI.spec
        echo "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)" >> CursorProGUI.spec
        echo "exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [], name='CursorProGUI', debug=False, bootloader_ignore_signals=False, strip=False, upx=True, upx_exclude=[], runtime_tmpdir=None, console=False)" >> CursorProGUI.spec
        
        # 使用 spec 文件构建
        pyinstaller CursorProGUI.spec
        
    - name: Upload Linux CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-Linux
        path: dist/CursorPro
        
    - name: Upload Linux GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorProGUI-Linux
        path: dist/CursorProGUI

  build-macos-intel:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        arch -x86_64 pip3 install --upgrade pip
        arch -x86_64 pip3 install pyinstaller
        arch -x86_64 pip3 install -r requirements.txt

    - name: Build MacOS Intel executable (CLI Version)
      env:
        TARGET_ARCH: 'x86_64'
      run: |
        arch -x86_64 python3 -m PyInstaller CursorKeepAlive.spec
        
    - name: Build MacOS Intel executable (GUI Version)
      env:
        TARGET_ARCH: 'x86_64'
      run: |
        # 创建新的spec文件
        echo "# -*- mode: python ; coding: utf-8 -*-" > CursorProGUI.spec
        echo "block_cipher = None" >> CursorProGUI.spec
        echo "a = Analysis(['cursor_pro_gui.py'], pathex=['$(pwd)'], binaries=[], datas=[('icons', 'icons'), ('translations', 'translations')], hiddenimports=[], hookspath=[], runtime_hooks=[], excludes=[], win_no_prefer_redirects=False, win_private_assemblies=False, cipher=block_cipher, noarchive=False)" >> CursorProGUI.spec
        echo "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)" >> CursorProGUI.spec
        echo "exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [], name='CursorProGUI', debug=False, bootloader_ignore_signals=False, strip=False, upx=True, upx_exclude=[], runtime_tmpdir=None, console=False)" >> CursorProGUI.spec
        
        # 使用 spec 文件构建
        arch -x86_64 python3 -m PyInstaller CursorProGUI.spec
        
    - name: Upload MacOS Intel CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-MacOS-Intel
        path: dist/CursorPro
        
    - name: Upload MacOS Intel GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorProGUI-MacOS-Intel
        path: dist/CursorProGUI

  create-release:
    needs: [build-windows, build-macos-arm64, build-linux, build-macos-intel]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create release archives
        run: |
          cd artifacts
          zip -r CursorPro-Windows.zip CursorPro-Windows/
          zip -r CursorProGUI-Windows.zip CursorProGUI-Windows/
          zip -r CursorPro-MacOS-ARM64.zip CursorPro-MacOS-ARM64/
          zip -r CursorProGUI-MacOS-ARM64.zip CursorProGUI-MacOS-ARM64/
          zip -r CursorPro-Linux.zip CursorPro-Linux/
          zip -r CursorProGUI-Linux.zip CursorProGUI-Linux/
          zip -r CursorPro-MacOS-Intel.zip CursorPro-MacOS-Intel/
          zip -r CursorProGUI-MacOS-Intel.zip CursorProGUI-MacOS-Intel/


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/CursorPro-Windows.zip
            artifacts/CursorProGUI-Windows.zip
            artifacts/CursorPro-MacOS-ARM64.zip
            artifacts/CursorProGUI-MacOS-ARM64.zip
            artifacts/CursorPro-Linux.zip
            artifacts/CursorProGUI-Linux.zip
            artifacts/CursorPro-MacOS-Intel.zip
            artifacts/CursorProGUI-MacOS-Intel.zip

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}